version: '3'
services:
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub
    ports:
      - '4444:4444'
  chrome:
    container_name: selenium-node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
  firefox:
    container_name: selenium-firefox-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    image: selenium/node-firefox
    volumes:
      - /dev/shm:/dev/shm
